version: "2"
services:
  rpc:
    image: manaphp/php73:2.0
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - ../:/var/www/html
      - /data/volumes/${COMPOSE_PROJECT_NAME}/rpc/data:/var/www/html/data
      - /data/volumes/${COMPOSE_PROJECT_NAME}/rpc/tmp:/var/www/html/tmp
    command: php /var/www/html/public/index.php
    ports:
      - ${WEB_PORT}:9501
    restart: always